appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Yl98uYo6pjc267KdaDmkLvvzFWYJ6yIxYHhoRLOktluncuptfuOEckQ15nT3w+MZ5JQZ38P8iy9nvinVr0n96LEr/DNplHbzQ4sNrbKN2asjQRMH4bA9zQ2+X1VDpZIX6DSIxHgjrkjdurBG5wLgZwvhkhYOLKWqJrlPtCZfeKw1/t0AT4uI6yXamsn5LRmVbUSPQzbuFhSy/03tw6ZR9Ri6aJimcEgHY0Lmoyqo7hxHLvvSsaUC3Nadps0F2VzuHvz26fR2Gl3PYcgi+zDq4ZcVZaUQr1J5fk5w9vqUJWcwXCJsNV3lkz5X+zea+GfhbroPyl5Qlv+JkVjl6nmjd4OyNBJ8AsL1rVcGF5LLRKITYL9CaYk95/ZugTe5JCxHiF6gF2UPzYnKPGPV568WkLojoJe/5wUR13uSICaw7TWwc4bpOOCir4fb12ZCWgqSRTSxo90se+N3A2fsVIUowNKsh9zWhoabFUgn5tP0BnIPpzMEwWtqNvpLDq2I6OB+jUkEwH1rOL07KZUlql/lz7CpDUrCxH4XJB+YT5Zufb0Z0J4roK/5dMEZvGqOsID1qunjffhobzzHa/BpzPkO3S2ZDZ+k4MPeYFv/7Do9qevB8Yh8/Ff7+Byo1wq1iCEarDgPZybXsurW8KIMgmRw4/UfIUq8zQoC2303vjj02vQ=
conda_forge_output_validation: true
